### ISSUE TITLE
#Remedy-List

### ISSUE THREAD

**Issue by Rahaf91** [Rahaf91/web-challenges#8]
## Value Proposition

**As a user**

**I want to** browse a list of remedies,

**so that** I can discover natural remedies for my health concerns.

## Description

Capstone Group Todo: Add wireframes

## Acceptance Criteria

- The homepage displays a list of remedies.
- The remedies list is headlined with its purpose.
- Each remedy listing includes:
  - Remedy title
  - Remedy image
  - Symptoms the remedy can address
- The list supports vertical scrolling to accommodate multiple entries.

## Tasks

- [ ] Create feature branch `feature/remedies-list`
- [ ] Inspect and adapt the example data in the [assets folder](./assets/remedies.json)
- [ ] Add an `imageUrl` for each remedy, for example from [unsplash.com](https://unsplash.com)
- [ ]   Create a component **RemediesList** to display all remedies
- [ ]  RemediesList props are: image,title, symptoms
